services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-dev
    restart: unless-stopped
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/config/passwd:/mosquitto/config/passwd
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - app_network
    ports:
      # WebSocket Port (for testing web UI)
      - "9001:9001"
      # Standard MQTT port (for testing ESP32)
      - "1883:1883"

networks:
  app_network:
    driver: bridge