name: Embedded CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
  push:
    branches:
      - main

concurrency:
  group: embedded_ci-${{ github.event.pull_request.head.ref || github.ref }}
  cancel-in-progress: true

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      is_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          files: |
            iot-smart-bin/embedded/**
            .github/workflows/embedded_ci.yaml

      - name: Log changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Changes detected in the following files:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Log no changes
        if: steps.changed-files.outputs.any_changed != 'true'
        run: echo "No changes detected in backend files."

  embedded_ci:
    needs: detect_changes
    if: needs.detect_changes.outputs.is_changed == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: iot-smart-bin/embedded
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Cache PlatformIO and pip packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
          restore-keys: |
            ${{ runner.os }}-pio-
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Check PlatformIO Project
        run: pio check
      
      - name: Build PlatformIO Project
        run: pio run --environment production
        env:
          PLATFORMIO_BUILD_FLAGS: -DCI_BUILD